# Generated by Django 4.2.7 on 2023-11-12 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                (
                    "quality",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("like_service_speed", models.BooleanField(default=False)),
                ("like_interface", models.BooleanField(default=False)),
                ("like_assortment", models.BooleanField(default=False)),
                ("comment", models.CharField(max_length=255)),
            ],
        ),
    ]
